// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCeN7eN1zBsRhfTNS4f0sAEWs2svI2qGhY',
    appId: '1:695567010914:web:2754aad4d322426359553b',
    messagingSenderId: '695567010914',
    projectId: 'dg-vocab',
    authDomain: 'dg-vocab.firebaseapp.com',
    storageBucket: 'dg-vocab.firebasestorage.app',
    measurementId: 'G-LL6N8960JP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA0HhNcciPvAmlQcS9coaJTYZHamT5G_2o',
    appId: '1:695567010914:android:f4560764931ec21559553b',
    messagingSenderId: '695567010914',
    projectId: 'dg-vocab',
    storageBucket: 'dg-vocab.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCjJFR-QnjImHCTvRbd_tWoc8MgXB7IkZM',
    appId: '1:695567010914:ios:2f3bfa13f72a101b59553b',
    messagingSenderId: '695567010914',
    projectId: 'dg-vocab',
    storageBucket: 'dg-vocab.firebasestorage.app',
    iosBundleId: 'com.example.toDoList',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCjJFR-QnjImHCTvRbd_tWoc8MgXB7IkZM',
    appId: '1:695567010914:ios:2f3bfa13f72a101b59553b',
    messagingSenderId: '695567010914',
    projectId: 'dg-vocab',
    storageBucket: 'dg-vocab.firebasestorage.app',
    iosBundleId: 'com.example.toDoList',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCeN7eN1zBsRhfTNS4f0sAEWs2svI2qGhY',
    appId: '1:695567010914:web:2ac64746b14b515b59553b',
    messagingSenderId: '695567010914',
    projectId: 'dg-vocab',
    authDomain: 'dg-vocab.firebaseapp.com',
    storageBucket: 'dg-vocab.firebasestorage.app',
    measurementId: 'G-NRNBV8W0K4',
  );
}
